/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VISTAS;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import veterinaria_MODELO.Mascota;
import veterinaria_MODELO.Tratamiento;
import veterinaria_MODELO.Visita;

/**
 *
 * @author Barbara
 */
public class Ficha_TRATAMIENTOS extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ficha_CLIENTE2
     */
    public Ficha_TRATAMIENTOS() {
        initComponents();
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        llenarListaTratamientos();
        jTableTratamientos.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel(){
            String str="/IMAGENES/fondo_TRATAMIENTO.png";
            ImageIcon icon = new ImageIcon(getClass().getResource(str));
            Image image = icon.getImage();

            public void paintComponent(Graphics g) {
                super.paintComponent(g);
                g.drawImage(image, 0, 0,getWidth(),getHeight(), this);
            }
        };
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jlDNI = new javax.swing.JLabel();
        jlN_DE_CLIENTE = new javax.swing.JLabel();
        jlCONTACTO_ALTERNATIVO = new javax.swing.JLabel();
        jlAPELLIDO2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jrbACTIVO = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableTratamientos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jlAPELLIDO3 = new javax.swing.JLabel();
        jtTratamientoN = new javax.swing.JTextField();
        jtTratamientoTipo = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jtTratamientoMedicacion = new javax.swing.JTextField();
        jtTratamientoPrecio = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jlLISTAR_Tratamientos = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 580, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 580, 10));

        jlDNI.setBackground(new java.awt.Color(255, 255, 255));
        jlDNI.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlDNI.setForeground(new java.awt.Color(255, 255, 255));
        jlDNI.setText("Tipo:");
        jPanel1.add(jlDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jlN_DE_CLIENTE.setBackground(new java.awt.Color(255, 255, 255));
        jlN_DE_CLIENTE.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlN_DE_CLIENTE.setForeground(new java.awt.Color(255, 255, 255));
        jlN_DE_CLIENTE.setText(" Tratamiento N°:");
        jPanel1.add(jlN_DE_CLIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jlCONTACTO_ALTERNATIVO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlCONTACTO_ALTERNATIVO.setForeground(new java.awt.Color(255, 255, 255));
        jlCONTACTO_ALTERNATIVO.setText("Precio :");
        jPanel1.add(jlCONTACTO_ALTERNATIVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 70, 20));

        jlAPELLIDO2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlAPELLIDO2.setForeground(new java.awt.Color(255, 255, 255));
        jlAPELLIDO2.setText("Medicacion:");
        jPanel1.add(jlAPELLIDO2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 20));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 590, 20));

        jrbACTIVO.setBackground(new java.awt.Color(255, 255, 255));
        jrbACTIVO.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jrbACTIVO.setText("Activo");
        jrbACTIVO.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jrbACTIVO.setEnabled(false);
        jPanel1.add(jrbACTIVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 70, 20));

        jTableTratamientos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tratamiento", "Descripcion", "Medicamento", "Precio", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableTratamientos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 560, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/close.png"))); // NOI18N
        jLabel2.setToolTipText("Salir de tratamiento");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 60, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/add.png"))); // NOI18N
        jLabel3.setToolTipText("Agregar un tratamiento con los campos en el formulario");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 60, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/delete.png"))); // NOI18N
        jLabel4.setToolTipText("Borrar el tratamiento que se encontro por busqueda  y se cargo al formulario");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 60, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/edit.png"))); // NOI18N
        jLabel5.setToolTipText("Permite actualizar el tratamiento que se busco previamente y se cargo al formulario");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 60, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/search.png"))); // NOI18N
        jLabel6.setToolTipText("Buscar un tratamiento, por ID o por una Lista");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 60, 50));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 610, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/clear.png"))); // NOI18N
        jLabel7.setToolTipText("Limpia todos los campos del formulario");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 60, 50));

        jlAPELLIDO3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlAPELLIDO3.setForeground(new java.awt.Color(255, 255, 255));
        jlAPELLIDO3.setText("Descripcion :");
        jPanel1.add(jlAPELLIDO3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 20));

        jtTratamientoN.setEnabled(false);
        jPanel1.add(jtTratamientoN, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 80, -1));
        jPanel1.add(jtTratamientoTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 170, 250, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 380, 50));
        jPanel1.add(jtTratamientoMedicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 380, -1));
        jPanel1.add(jtTratamientoPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 90, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel8.setText("$");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 10, 20));

        jlLISTAR_Tratamientos.setBackground(new java.awt.Color(51, 51, 255));
        jlLISTAR_Tratamientos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlLISTAR_Tratamientos.setForeground(new java.awt.Color(255, 255, 255));
        jlLISTAR_Tratamientos.setText(" LISTAR TRATAMIENTOS");
        jlLISTAR_Tratamientos.setToolTipText("Presione aqui para recargar los tratamientos existentes");
        jlLISTAR_Tratamientos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jlLISTAR_Tratamientos.setOpaque(true);
        jlLISTAR_Tratamientos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlLISTAR_TratamientosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlLISTAR_TratamientosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlLISTAR_TratamientosMouseExited(evt);
            }
        });
        jPanel1.add(jlLISTAR_Tratamientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        limpiarFormulario();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void limpiarFormulario() {
        jtTratamientoN.setText("");
        jtTratamientoTipo.setText("");
        jTextArea1.setText("");
        jtTratamientoMedicacion.setText("");
        jtTratamientoPrecio.setText("");
        jrbACTIVO.setEnabled(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
    }

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // mostrar opcion de buscar por id o seleccionar de una lista
        int result = JOptionPane.showOptionDialog(this, "¿Desea buscar por ID de tratamiento o seleccionar de una lista?", "Seleccione el metodo de busqueda", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"ID", "Lista"}, "");
        if (result == JOptionPane.YES_OPTION) {
            // buscar por id
            int id = Integer.parseInt(JOptionPane.showInputDialog("Ingrese el ID del tratamiento"));
            Tratamiento tratamiento = Menu_PRINCIPAL_VETERINARIA.td.buscarTratamientoActivo(id);
            if (tratamiento == null) {
                tratamiento = Menu_PRINCIPAL_VETERINARIA.td.buscarTratamientoInactivo(id);
            }
            if (tratamiento == null) {
                JOptionPane.showMessageDialog(this, "No se encontro el tratamiento");
            } else {
                rellenarFormulario(tratamiento);
            }

        } else if (result == JOptionPane.NO_OPTION) {
            List<Tratamiento> tratamientoList = Menu_PRINCIPAL_VETERINARIA.td.obtenerTratamientos();
            // mostrar lista de tratamientos en un JPanel usando un combobox
            JPanel panel = new JPanel();
            JComboBox<Tratamiento> comboBox = new JComboBox<>();
            for (Tratamiento tratamiento : tratamientoList) {
                comboBox.addItem(tratamiento);
            }
            panel.add(comboBox);
            int result2 = JOptionPane.showOptionDialog(this, panel, "Seleccione el tratamiento", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, "");
            if (result2 == JOptionPane.OK_OPTION) {
                Tratamiento tratamiento = (Tratamiento) comboBox.getSelectedItem();
                rellenarFormulario(tratamiento);
            }
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jlLISTAR_TratamientosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlLISTAR_TratamientosMouseClicked
        llenarListaTratamientos();
    }//GEN-LAST:event_jlLISTAR_TratamientosMouseClicked

    public void llenarListaTratamientos() {
        // cargar la lista de tratamientos en un JTable2
        List<Tratamiento> tratamientoList = Menu_PRINCIPAL_VETERINARIA.td.obtenerTratamientos();
        DefaultTableModel model = (DefaultTableModel) jTableTratamientos.getModel();
        model.setRowCount(0); // BORRA TODAS LAS LINEAS Y VUELVE A 0//

        for (Tratamiento t1 : tratamientoList) {
            model.addRow(new Object[]{t1.getId_tratamiento(), t1.getTipo_tratamiento(), t1.getDescripcion(), t1.getMedicamento(), t1.getPrecio(), t1.isActivo()});
        }
    }
    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // check if jTratamientoN is not empty, then ask if user wants to delete tratamiento
        if (!jtTratamientoN.getText().isEmpty()) {
            int result = JOptionPane.showOptionDialog(this, "¿Desea eliminar el tratamiento?", "Eliminar tratamiento ID: " + jtTratamientoN.getText(), JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Si", "No"}, "");
            if (result == JOptionPane.YES_OPTION) {
                // delete tratamiento
                Menu_PRINCIPAL_VETERINARIA.td.borrarTratamiento(Integer.parseInt(jtTratamientoN.getText()));
                JOptionPane.showMessageDialog(this, "Tratamiento eliminado");

            } else if (result == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "Tratamiento no eliminado");
            }
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // validar el formulario, entonces actualizar el tratamiento
        // preguntar si se desea actualizar el tratamiento con un joptionpane
        int result = JOptionPane.showOptionDialog(this, "¿Desea actualizar el tratamiento?", "Actualizar tratamiento ID: " + jtTratamientoN.getText(), JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Si", "No"}, "");
        if (result == JOptionPane.YES_OPTION) {
            if (validarFormulario()) {
                Tratamiento tratamiento = crearUnTratamientoDesdeForm();
                Menu_PRINCIPAL_VETERINARIA.td.modificarTratamiento(Integer.parseInt(jtTratamientoN.getText()), tratamiento);
                JOptionPane.showMessageDialog(this, "Tratamiento actualizado");
                limpiarFormulario();
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo actualizar el tratamiento");
            }
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Tratamiento no actualizado");
        }


    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // validar el formulario, entonces guardar el tratamiento
        // preguntar si se desea guardar el tratamiento con un joptionpane
        int result = JOptionPane.showOptionDialog(this, "¿Desea guardar el tratamiento?", "Guardar tratamiento", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Si", "No"}, "");
        if (result == JOptionPane.YES_OPTION) {
            if (validarFormulario()) {
                Tratamiento tratamiento = crearUnTratamientoDesdeForm();
                Menu_PRINCIPAL_VETERINARIA.td.agregar_Tratamiento(tratamiento);
                JOptionPane.showMessageDialog(this, "Tratamiento guardado");
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo guardar el tratamiento");
            }
        } else if (result == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Tratamiento no guardado");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jlLISTAR_TratamientosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlLISTAR_TratamientosMouseEntered
        jlLISTAR_Tratamientos.setBackground(new Color(100,100,255));
    }//GEN-LAST:event_jlLISTAR_TratamientosMouseEntered

    private void jlLISTAR_TratamientosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlLISTAR_TratamientosMouseExited
       jlLISTAR_Tratamientos.setBackground(new Color(51,51,255));
    }//GEN-LAST:event_jlLISTAR_TratamientosMouseExited

    private boolean validarFormularioParaModificar() {
        if (jtTratamientoN.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El ID del tratamiento no puede estar vacio");
            return false;
        } else {
            return validarFormulario();
        }
    }

    private boolean validarFormulario() {
        if (jTextArea1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La descripcion del tratamiento no puede estar vacia");
            jTextArea1.requestFocus();
            return false;
        }
        if (jtTratamientoPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El precio del tratamiento no puede estar vacio");
            jtTratamientoPrecio.requestFocus();
            return false;
        }

        return true;
    }

    private Tratamiento crearUnTratamientoDesdeForm() {
        Tratamiento tratamiento = new Tratamiento();
        tratamiento.setTipo_tratamiento(jtTratamientoTipo.getText());
        tratamiento.setDescripcion(jTextArea1.getText());
        tratamiento.setMedicamento(jtTratamientoMedicacion.getText());
        tratamiento.setPrecio(Double.parseDouble(jtTratamientoPrecio.getText()));
        tratamiento.setActivo(jrbACTIVO.isSelected());
        return tratamiento;
    }

    private void rellenarFormulario(Tratamiento tratamiento) {
        if (tratamiento.isActivo()) {
            jtTratamientoN.setText(Integer.toString(tratamiento.getId_tratamiento()));
            jtTratamientoTipo.setText(tratamiento.getTipo_tratamiento());
            jTextArea1.setText(tratamiento.getDescripcion());
            jtTratamientoMedicacion.setText(tratamiento.getMedicamento());
            jtTratamientoPrecio.setText(String.valueOf(tratamiento.getPrecio()));
            jrbACTIVO.setSelected(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
        } else {
            // preguntar si desea activar el tratamiento
            int result = JOptionPane.showOptionDialog(this, "¿El tratamiento esta inactivo desea activar el tratamiento?", "Tratamiento inactivo ID: " + tratamiento.getId_tratamiento(), JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new String[]{"Si", "No"}, "");
            if (result == JOptionPane.YES_OPTION) {
                // activar tratamiento
                jrbACTIVO.setSelected(true);
                Menu_PRINCIPAL_VETERINARIA.td.activarTratamiento(tratamiento.getId_tratamiento());
                JOptionPane.showMessageDialog(this, "Tratamiento activado");
                jLabel4.setVisible(true);
                jLabel5.setVisible(true);
            } else if (result == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(this, "Tratamiento no activado");
                jrbACTIVO.setSelected(false);
                jLabel4.setVisible(false);
                jLabel5.setVisible(false);
            }
            jtTratamientoN.setText(Integer.toString(tratamiento.getId_tratamiento()));
            jtTratamientoTipo.setText(tratamiento.getTipo_tratamiento());
            jTextArea1.setText(tratamiento.getDescripcion());
            jtTratamientoMedicacion.setText(tratamiento.getMedicamento());
            jtTratamientoPrecio.setText(String.valueOf(tratamiento.getPrecio()));
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableTratamientos;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel jlAPELLIDO2;
    private javax.swing.JLabel jlAPELLIDO3;
    private javax.swing.JLabel jlCONTACTO_ALTERNATIVO;
    private javax.swing.JLabel jlDNI;
    private javax.swing.JLabel jlLISTAR_Tratamientos;
    private javax.swing.JLabel jlN_DE_CLIENTE;
    private javax.swing.JRadioButton jrbACTIVO;
    private javax.swing.JTextField jtTratamientoMedicacion;
    private javax.swing.JTextField jtTratamientoN;
    private javax.swing.JTextField jtTratamientoPrecio;
    private javax.swing.JTextField jtTratamientoTipo;
    // End of variables declaration//GEN-END:variables
}
